### ISSUE TITLE
Error: command option with prompt leads to an Unknown argument Error

### ISSUE THREAD

**Issue by arbue** [hongaar/bandersnatch#186]
Hello,

if I try to run the following command in repl mode:

```javascript
const connectCmd = command('connect', { description: 'connect' })
  .option('host', { description: 'hostname', type: 'string', prompt: true })
  .action(async (args) => {
      console.log('do something with args ' + args);
  });
 
 const repl = program({ help: true })
        .add(connectCmd);
 repl.repl();
```

It prompts me to add a value correctly but then it fails with the StackTrace below:
`
> connect
? hostname ‣ asd
Error: Unknown argument: asd
    at Program.failHandler (/node_modules/bandersnatch/lib/program.js:165:19)
    at Object.fail (/node_modules/bandersnatch/node_modules/yargs/build/index.cjs:692:25)
    at Object.unknownArguments (node_modules/bandersnatch/node_modules/yargs/build/index.cjs:1500:19)
    at Object.runValidation [as _runValidation] /node_modules/bandersnatch/node_modules/yargs/build/index.cjs:2821:26)
    at Object.parseArgs [as _parseArgs] (/node_modules/bandersnatch/node_modules/yargs/build/index.cjs:2764:26)
    at Object.parse (/node_modules/bandersnatch/node_modules/yargs/build/index.cjs:2278:29)
    at /node_modules/bandersnatch/lib/program.js:96:40
    at new Promise (<anonymous>)
    at Program.run (/node_modules/bandersnatch/lib/program.js:95:16)
    at Repl.eval (/node_modules/bandersnatch/lib/repl.js:75:47)
✔ hostname · asd
do something with args [object Object]
`

Version:
1.3.8

**Comment by hongaar** [comment]
Hi @arbue, thanks for reporting this. I was able to reproduce it and I'm working on a fix. Will report back when it's been resolved.

**Comment by hongaar** [comment]
This should be fixed with https://github.com/hongaar/bandersnatch/pull/188 (release coming up).
Can you try the new version and let me know if you still encounter this problem?
